//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventorySystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inv_systemEntities : DbContext
    {
        public inv_systemEntities()
            : base("name=inv_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_product> tbl_product { get; set; }
        public virtual DbSet<tbl_purchase> tbl_purchase { get; set; }
        public virtual DbSet<tbl_sale> tbl_sale { get; set; }
    }
}
