//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_purchase
    {
        public int poID { get; set; }
        public string poName { get; set; }
        public Nullable<System.DateTime> poDate { get; set; }
        public string proQty { get; set; }
    }
}
