//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sale
    {
        public int saleID { get; set; }
        public string saleName { get; set; }
        public Nullable<System.DateTime> saleDate { get; set; }
        public string saleQty { get; set; }
    }
}
